baseURL = "https://www.bdathe.wiki/"
title = "bdathe@home"
theme = "hugo-theme-console"
languageCode = "zh-cn"

[params]
  animateStyle = "animate-fade-up"

[[params.navlinks]]
  name = "about/"
  url = "/about/"

[[params.navlinks]]
  name = "posts/"
  url = "/posts/"

[[params.navlinks]]
  name = "music/"
  url = "/music/"

[[params.navlinks]]
  name = "photos/"
  url = "/photos/"
